### ISSUE TITLE
Fish Dupe Bug

### ISSUE THREAD

**Issue by CallofParanoia** [Vaygrim/wasted#35]
- Use any fish in a Pam's HarvestCraft grinder to get 2x Ground Fish. 

- Then crafting the Ground Fish into a vanilla fish in any crafting grid. 

- Repeat.

**Comment by FoxBotGames** [comment]
The recipe: Ground Fish to Vanilla Fish is a recipe by Pam's Harvestcraft that is causing this issue, seems Pam (im just going to say) missed it.
Its a simple fix, just remove the recipe, too bad this fox has no clue how to do it XD

**Comment by FoxBotGames** [comment]
Well... Me being ignorant and having MallRat explain a few things to me its not that simple.

**Comment by CallofParanoia** [comment]
Is there a way to modify the recipe to the following: 2 x Ground Fish = Vanilla Fish?

**Comment by CallofParanoia** [comment]
Mmm... 
Recipe seems to be OreDict. 
ListAllFishRaw = minecraft:fish /0

**Comment by Vaygrim** [comment]
This is, unfortunately something that needs to be reported directly to .. and handled by.. Pam's HarvestCraft developers. It is an uncaught oversight on Pam's part and due to the sheer scope of items and recipes involved in it, puts it will outside of this team's scope of resolution.

We will pass this onto the HarvestCraft team but at this time, will be considered this a closed issue on our end. Thank you!
