### ISSUE TITLE
Lead Nuggets

### ISSUE THREAD

**Issue by SOTMead** [Vaygrim/wasted#47]
A Thermal Foundation lead ingot is shown to give TF lead nuggets in JEI. It instead gives Techguns lead nuggets.

The TG shotgun shell recipe calls for TF lead nuggets but will not accept TG lead nuggets. The copper nuggets in that recipe say 'accepts any nuggetCopper', the lead ones do not say that.

There isn't a way to convert TG lead nuggets to TF, and TG lead nuggets have no other use. The TG lead nuggets don't even show up in JEI.

So all this renders the TG shotgun shells unavailable unless an op interferes.

**Comment by FoxBotGames** [comment]
Issue Already Solved:
TG Lead wont show up in JEI for use because TG Lead was disabled to prevent multiple ore generation, the initial issue was that the TF Ingot was converting to _disabled_ TG Nuggets that were not useable.
This has been fixed, however TG lead will continue to not have a use in JEI (reason why I can't answer)

Next Update this should be fixed.

**Comment by mallrat208** [comment]
That problem stems from tech guns. It's config option to disable it's items only removed their ore dictionary registration. Any recipes they add are still in place.

We need to either change the config option in Tech Guns to enable it's ingots, nuggets, etc. or we need to add the to the ore dictionary manually using Craft Tweaker

**Comment by FoxBotGames** [comment]
Fixed: TG Lead should now show up in JEI as of next update

**Comment by Vaygrim** [comment]
This is fixed as of the 1.0.4 update, which should be rolling out later tonight.
