### ISSUE TITLE
In the Begining/Food? not repeatable.

### ISSUE THREAD

**Issue by jengeld4** [Vaygrim/wasted#51]
Version: 1.0.6

This quest seems to be set up to be a repeatable quest exchanging dirt for gardens. I can complete it once, but it seem the repeat timer is actually stuck in -10ish until -59, then resets preventing the cool down timer from actually ending.
![2018-05-02_11 20 21](https://user-images.githubusercontent.com/10388293/39535959-dcce20d4-4dfa-11e8-85b9-c32da4b69217.png)

**Comment by FoxBotGames** [comment]
(Request Bug Tag For this issue)
Is this on a server or single player? If server: Log out and back in or restart server. Make sure you are using the latest forge version. (let me know if any of these help or not)

Better Questing has a new update as of today that has UI rewrites and attempts at bug fixes. Wasted will be getting an update hopefully this week.

If this does not get fixed with the new update I will report it to BQ (even tho the last hundred reports by various people haven't been touched by the dev)
(Writer of the Wasted Quests)

**Comment by jengeld4** [comment]
It's single player. Might be the result of updating the pack, but I don't think it is.

**Comment by FoxBotGames** [comment]
Need to know if the new version (1.0.7) kept this bug.
If it is still there try **/bq_admin default load** this might reset the quest's timer if it continues to persist as is let me know.

**Comment by jengeld4** [comment]
Updated and reloaded quest. No such luck.

**Comment by FoxBotGames** [comment]
Doing some testing and research, I have found out this issue dates back to when the quests where just starting to be made (Wasted Version 0.0.3 - BQ Version 3.5.238). According to the dev from a previous issue of close to the same issue without a stable previous version there is no way to fix this. (I think it's because he is rewriting the UI...) For now I think I will have to find a way around this issue while I wait for a response from the BQ dev

**Comment by FoxBotGames** [comment]
BQ dev commented saying you might have Edit Mode turned on even when you don't have permissions to Edit.
Recommend running **/bq_admin edit**
If that returns the 'no permissions' or something like that you will have to enable cheats and then run the command....
I am still trying to find a way to prevent this in future instances

**Comment by FoxBotGames** [comment]
Edit mode off Caused notification spam, have to change dependency of the quests from repeatable to something else due to known bug. Next Wasted update should fix this

**Comment by FoxBotGames** [comment]
Issue Fixed as of Version 1.0.7
