### ISSUE TITLE
cyberdemons for techguns

### ISSUE THREAD

**Issue by diablopotatos** [Vaygrim/wasted#60]
techguns.cfg file cyberdemon spawn are set to 0

**Comment by XEridaniTribalX** [comment]
We turned them off completely, because they are horrible abominations that were nearly impossible to kill, and they ended up completely overrunning the Nether, which ended up crowding out other mobs.

**Comment by FoxBotGames** [comment]
This is because after long rigorous testing we found that regardless of how low we set them to spawn they still spawned in like a wildfire in a dry savanna. It made going through the nether nearly impossible.
Their guns ignore armor and knock you back, so they stun locked you and then killed you in 4 or so shots. 
Be my guest and up the setting on your own files for increased difficulty if you would like.

**Comment by diablopotatos** [comment]
the cyber part that drop from them u need to the build fabricator and reaction chamber that need it

**Comment by FoxBotGames** [comment]
Not needed, we changed the recipe. The recipe now requires an elite circuit from Mekanism or Techguns. Make sure you have the TG2.zs under scripts in the instance folder. (Not inside config folder)

**Comment by diablopotatos** [comment]
sorry my bad i am new how githud work
